# SEP-1 template: complete these fields for your RWA Launchpad asset identity.
# Publish this file on your domain (e.g. https://yourdomain.com/.well-known/stellar.toml)

VERSION = "1.0.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

[[CURRENCIES]]
code = "SXR"
issuer = "GAVEI4XYSBSLWXFWKVNHGN7H3P5M4GMVVHFHC43NVI7MHCIZPEZJYIHV"
status = "live"
display_decimals = 2
name = "Sasxr Token"
desc = "Real World Asset Token"
conditions = "This real-world asset backs sasxr securities "

[DOCUMENTATION]
ORG_NAME = "Sasxr"
ORG_OFFICIAL_EMAIL = "mrsblast@gmail.com"
